### ISSUE TITLE
Pageless format is inverted without using the invert option, while the text colour stays the same.

### ISSUE THREAD

**Issue by skalameraion** [waymondrang/docsafterdark#16]
![image](https://user-images.githubusercontent.com/32754510/192664283-b156d21b-502f-4dc3-a9d4-bb99933473e1.png)
![image](https://user-images.githubusercontent.com/32754510/192664330-92b09d20-cfa1-45e0-85ba-a1127fc1d8f2.png)

**Comment by waymondrang** [comment]
Thank you for opening an issue. Can you provide which browser you are using?

**Comment by skalameraion** [comment]
Chrome on Chrome OS, no other darkening extension, works normally with pages.

**Comment by waymondrang** [comment]
Thank you! This is normal behavior for the extension. Since the background color of the page is set to "Black," the pageless document will have a black background. The text color in your document is set to black, which is why it appears invisible. 

I would recommend setting the document background to "Dark" and enabling the invert and grayscale options. This way, the document background will be dark and the text readable. I hope this helps!
