### ISSUE TITLE
Misbehavior in various browsers

### ISSUE THREAD

**Issue by Ner-Kat** [waymondrang/docsafterdark#18]
With identical settings (and identical version - actual 0.5.2) i have not identical behavior of the extension (in the same file).
In Vivaldi (Chromium-based browser, extension from Chrome Store):
![image](https://user-images.githubusercontent.com/47861604/196523697-1df96d7e-b8bf-4ea1-9ed5-14208b815fb6.png)

In Firefox (extension from official store):
![image](https://user-images.githubusercontent.com/47861604/196524065-c3079de8-2696-4287-8cbb-a5afd46e137b.png)

Looks like a bug in Chromium-based browsers (I tested same file in the clear Chrome and had result as in Vivaldi).

**Comment by waymondrang** [comment]
Hello,

This is expected behavior as Google Docs is implemented differently for each browser. In Firefox, the image elements are separate from the document canvas, which is why they ignore the invert. However, in Chromium-based browsers, it seems that the images are rendered into the document canvas.
