### ISSUE TITLE
Firefox dark mode is basically unreadable

### ISSUE THREAD

**Issue by gorgonopsidkid** [waymondrang/docsafterdark#22]
For some reason my dark mode puts a weird white layer over the page which makes text unreadable. Changing background color and text color doesn't effect anything. I'm on Firefox with Windows 10 and I've turned all my extensions on and off with no change. It's been like this for a month at least.
![Capture-26](https://user-images.githubusercontent.com/120499994/207402608-697545f6-d646-4666-9bc9-970e46e6dada.PNG)
![Capture-28](https://user-images.githubusercontent.com/120499994/207402609-0e8b11f9-9b72-4fd0-92bf-d4b8978c8a59.PNG)

**Comment by waymondrang** [comment]
Hello,

Thank you for creating an issue. I apologize that the extension did not work as expected. I believe this issue may be caused by the non-white page color shown in the screenshot without dark mode. It also appears that you have enabled the invert option in DocsAfterDark. This may contribute to the low contrast page in your screenshot with dark mode.

Can you try to reproduce the issue with a white page color?

**Comment by vurtomatic** [comment]
Hi @waymondrang , I'm reporting the same thing on Firefox 108.0.2 (64-bit) and macOS Monterey 12.6.2.

![image](https://user-images.githubusercontent.com/7212035/210884242-997115bf-2657-4646-aea2-aad17854e8a1.png)

**Comment by waymondrang** [comment]
Hello, this is the expected behavior for DocsAfterDark on Firefox, as changing the background color should not also change the text color. I would recommend using the default background color with invert and grayscale enabled. If you are still experiencing invert problems or any other problems on the latest version, v1.0.0, please feel free to open another issue!
