### ISSUE TITLE
Text colour unchanged

### ISSUE THREAD

**Issue by stephenaustin** [waymondrang/docsafterdark#44]
Attempted to use Docsafterdark on Windows 11 using updated Firefox (121.01). When changing to 'dark' or 'black' modes, the text is unchanged. In 'black' mode, this of course makes the text unreadable. 

Can find no settings for changing font / text colour in the  extension.

**Comment by waymondrang** [comment]
Hello, this is the expected behavior for DocsAfterDark on Firefox, as changing the background color should not also change the text color. I would recommend using the default background color with invert and grayscale enabled. If you are still experiencing invert problems or any other problems on the latest version, v1.0.0, please feel free to open another issue!

**Comment by stephenaustin** [comment]
Thanks!
